services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: tws_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql_data_new:/var/lib/mysql
    networks:
      - twotier
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-padmin"]
      interval: 10s
      retries: 5
      start_period: 60s
      timeout: 5s
    restart: unless-stopped

  flaskapp:
    build: .
    container_name: flaskapp
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DB: tws_db
    networks:
      - twotier
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

#create a docker volume
volumes:
  mysql_data_new:

#create a docker network
networks:
  twotier:
